from typing import Any, Optional

from pydantic import BaseModel, ConfigDict, Field


class AgentResponse(BaseModel):
    """
    Structured output returned by an individual reasoning agent or challenger critique.

    Note: `self_reported_confidence` is treated strictly as agent metadata
    representing the persona's internal confidence self-estimate. It is NOT
    used as the final system confidence score, which is calculated independently
    by the Confidence Engine in Phase 6.
    """

    agent_name: str = Field(
        ...,
        description="Name/identifier of the reasoning persona (e.g., 'logical', 'challenger').",
    )
    answer: str = Field(
        default="",
        description="The detailed answer generated by the agent persona or critique summary.",
    )
    key_points: Any = Field(
        default_factory=list,
        description="List of concise bullet points or structured critique dictionary.",
    )
    self_reported_confidence: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Agent's self-estimated confidence (0.0 to 1.0) based on context evidence. Used only as metadata.",
    )
    latency_ms: float = Field(
        default=0.0, description="Execution latency of the agent in milliseconds."
    )
    error: Optional[str] = Field(
        default=None,
        description="Error message if the agent execution or API call failed.",
    )

    model_config = ConfigDict(from_attributes=True)
